### ISSUE TITLE
MorphToMany withPivot

### ISSUE THREAD

**Issue by Hesesses** [tylernathanreed/laravel-relation-joins#3] opened 2020-04-16 11:12 UTC
Hello,

Thank you very much for creating this package, it was a life saver for our project 🙏 

In our project we have `Event` and `Location` models with pivot table `location_relations`.
`location_relations`table has `location_type`field so we can attach different "locations" to the Event

We are having one problem with morphToMany wherePivot join:

```
// the join from getting Events (quite complicated, but the main thing is):
$this->builder->leftJoinRelation('locations');

// events.php
public function locations()
    {
        return $this->morphToMany(Location::class, 'object', 'location_relations')
            ->wherePivot('location_type', 'event_location'));
    }
```

The result is that the leftJoinRelation joins all locations ignoring the 
`->wherePivot('location_type', 'event_location')`

Are we doing something wrong or how this should work?

Greetings from Finland

**Comment by tylernathanreed** [comment] 2020-05-18 14:58
@Hesesses 

To address your issue, I started to work on adding two new test cases to cover the "wherePivot" functionality, but both appear to be already passing (indicating that there may not be an issue in the package).

Here's the setup for the Morph To Many using Where Pivot test:

```php
class Post extends Model
{
    public function tagsWherePivot()
    {
        return $this->morphToMany(Tag::class, 'taggable', 'taggables', 'taggable_id', 'tag_id', 'id')->wherePivot('scope', '=', 'global');
    }
}
```

Here's the usage within the new Test:

```php
$query = (new Post)->newQuery()->joinRelation('tagsWherePivot');
```

And this is the resulting SQL (assuming agnostic syntax):

```sql
select *
from "posts"
    inner join "taggables"
        on "taggables"."taggable_id" = "posts"."id"
            and "taggables"."taggable_type" = 'App\Models\Post' -- Or equivalent
    inner join "tags"
        on "tags"."id" = "taggables"."tag_id"
            and "taggables"."scope" = 'global'
```

I believe that in your scenario, you should be seeing the following:

```php
$query = (new Event)->newQuery()->leftJoinRelation('locations');
```

```sql
select *
from "events"
    left join "location_relations"
        on "location_relations"."object_id" = "events"."id"
            and "location_relations"."object_type" = 'App\Models\Event' -- Or equivalent
    left join "locations"
        on "locations"."id" = "location_relations"."location_id"
            and "location_relations"."location_type" = 'event_location'
```

This appears to be working from a direct approach, but your scenario appears to be more complex (as you're obtaining a builder instance from somewhere other than directly from the model itself).

It's possible that you're either doing something that prevents the package from properly applying the join, or you're improperly applying the join in a way that your application isn't able to pick up on.

In either case, I would need more information to help diagnose the problem. I'm currently under the impression that the package is working correctly, but I'm open to additional evidence that suggests otherwise.

I've leave this issue open for now, since the problem is unresolved. If you manage to find a solution, please let me know, so that I may close this issue. Otherwise, I'll only close the issue if it becomes stale (since again, I can't find any evidence on my end that what you're trying to do wouldn't work).

**Comment by Hesesses** [comment] 2020-05-18 17:40
Thank you for the reply!

I will do more testing and get back to this 🙏

**Comment by Hesesses** [comment] 2020-05-19 11:47
I played around with this and the query in our system is:
```
SELECT `events`.`id`, `events`.`name`, 
       `locations`.`city` AS `__sorted` 
FROM   `events` 
       LEFT JOIN `location_relations` 
              ON `location_relations`.`object_id` = `events`.`id` 
                 AND `location_relations`.`object_type` = 'App\Event' 
       LEFT JOIN `locations` 
              ON `locations`.`id` = `location_relations`.`location_id` 
                 AND `location_relations`.`location_type` = 'event_location' 
ORDER  BY `__sorted` ASC
```

Table data
```
events:
id	name
1	Event 1
2	Event 2
3	Event 3
4	Event 4
5	Event 5
6	Event 6
7	Event 7

location_relations:
id	object_id	object_type	location_id	location_type
121	1	        App\Event	1	        event_location	
122	1	        App\Event	88	        something_else	

locations:
id	city
1	Name of the city
```

The results of the query:

```
id	name	__sorted
1	Event 1	NULL
2	Event 2	NULL
3	Event 3	NULL
4	Event 4	NULL
5	Event 5	NULL
6	Event 6	NULL
7	Event 7	NULL
1	Event 1	Name of the city
```

The result I was expecting is without the first id 1 row.

I think the reason why the id = 1 row is shown twice is because the location_relations table has 2 relations to events table. I though this was a bug in the package, but as you said, it does work as it should and this is something else.

If you can quickly think a solution to solve this, i would really appreciate :pray:

This issue can be closed

**Comment by tylernathanreed** [comment] 2020-08-13 14:25
@Hesesses 

Yeah, this can be difficult with left joins. With the query that you had, if one of the lines of SQL were moved up to the pivot, your issue would be solved:

```sql
SELECT `events`.`id`, `events`.`name`, 
    `locations`.`city` AS `__sorted` 
FROM   `events` 
    LEFT JOIN `location_relations` 
        ON `location_relations`.`object_id` = `events`.`id` 
            AND `location_relations`.`object_type` = 'App\Event' 
            AND `location_relations`.`location_type` = 'event_location' (Put it here instead)
    LEFT JOIN `locations` 
        ON `locations`.`id` = `location_relations`.`location_id` 
         -- AND `location_relations`.`location_type` = 'event_location' (Don't put this here)
ORDER  BY `__sorted` ASC
```

But naturally, you're not writing the raw SQL here, you're using Eloquent. A solution that I would like to see (syntax wise) would be this:

```php
$query = (new Event)->newQuery()->leftJoinRelation('locations', function($join, $pivot) {
    $pivot->where('location_relations.location_type', '=', 'event_location');
});
```

Unfortunately, the second "`$pivot`" variable isn't really a thing. This is just how I would implement it. Given how queries are built under the hood, by the type I'm able to provide a closure to the query, the pivot join has already been performed. That makes achieving this functionality very difficult, but not impossible.

For the time being, I'm going to convert this to a feature request, as there's bound to be a way to pull this off.

**Comment by tylernathanreed** [comment] 2020-08-13 14:29
@Hesesses 

Also, in the mean time, you could use this workaround:

```php
$query = (new Event)->newQuery()->leftJoinRelation('locationRelations', function($join) {
    $join->where('location_relations.location_type', '=', 'event_location');
})->leftJoinThroughRelation('locationRelations.locations');
```

Essentially, you'd have to define a relation to your pivot model, and a relation on said pivot model to the locations. It works, but it's not as elegant as the utopian solution I outlined in my previous comment.

**Comment by tylernathanreed** [comment] 2021-07-07 15:16
@Hesesses,

It was a long battle, but I can finally close this issue!

As of the latest release, you can now specify pivot constraints, and it can be done in the way that I had hoped:

```php
$query = (new Event)->newQuery()->leftJoinRelation('locations', function($join, $pivot) {
    $pivot->where('location_relations.location_type', '=', 'event_location');
});
```

Refer to the documentation to see everything else you can do with pivots now, which includes query scopes and soft deletes.

**Closed by tylernathanreed** 2021-07-07 15:16 UTC
Labels: Enhancement
